// exporters/index.js - Export all file type exporters

import { DEFAULT_PROJECT_FILE_STRUCTURE } from '../../config/config';

// Helper function to normalize scenarioData format
// Handles both array format (from parser) and object format (from DEFAULT_PROJECT_FILE_STRUCTURE)
function getFilenamesForExtension(scenarioData, ext) {
    const data = scenarioData[ext];

    // If it's already an array, return it
    if (Array.isArray(data)) {
        return data;
    }

    // If it's an object with a filename property, return array with that filename (if not empty)
    if (data && typeof data === 'object' && 'filename' in data) {
        return data.filename ? [data.filename] : [];
    }

    // Default to empty array
    return [];
}

// Scenario Exporter
export function exportScenarioFile(scenarioData, settingsData) {
    // Get scenario name - handle both array and object formats
    let scenarioName = 'Unnamed';
    if (scenarioData.scenario) {
        if (Array.isArray(scenarioData.scenario)) {
            scenarioName = scenarioData.scenario[0] || 'Unnamed';
        } else if (typeof scenarioData.scenario === 'object' && scenarioData.scenario.filename) {
            scenarioName = scenarioData.scenario.filename || 'Unnamed';
        }
    }

    let scenarioOutput = `// SCENARIO DEFINITION - ${scenarioName}\n`;
    scenarioOutput += "// Generated by scenario_exporter\n";
    scenarioOutput += "// ifset key: 0x01: Load CVP; 0x02: Load Rest of Source; 0x03: Load all; 0x04: Load Cache\n\n";

    // #ifset 0x01 section
    scenarioOutput += "#ifset 0x01\n";
    for (const ext of ['cvp', 'regionincl', 'prf']) {
        const filenames = getFilenamesForExtension(scenarioData, ext);
        for (const filename of filenames) {
            const dirPath = getDirectoryForExtension(ext);
            const fullFilename = `${filename}.${ext.toUpperCase()}`;
            scenarioOutput += `#include "${fullFilename}", "${dirPath}"\n`;
        }
    }
    scenarioOutput += "#endifset\n\n";

    // #ifset 0x02 section
    scenarioOutput += "#ifset 0x02\n";
    for (const ext of ['unit', 'pplx', 'ttrx', 'terx', 'wmdata', 'newsitems']) {
        const filenames = getFilenamesForExtension(scenarioData, ext);
        for (const filename of filenames) {
            const dirPath = getDirectoryForExtension(ext);
            const fullFilename = `${filename}.${ext.toUpperCase()}`;
            scenarioOutput += `#include "${fullFilename}", "${dirPath}"\n`;
        }
    }
    scenarioOutput += '#include "AllSourceLoad.INI", "INI\\"\n';
    scenarioOutput += "#endifset\n\n";

    // &&MAP section
    scenarioOutput += "&&MAP\n";
    const mapxFilenames = getFilenamesForExtension(scenarioData, 'mapx');
    if (mapxFilenames.length > 0) {
        const mapName = mapxFilenames[0].split('.')[0];
        scenarioOutput += `mapfile "${mapName}"\n`;
    }
    scenarioOutput += "&&END\n\n";

    // Other includes
    for (const ext of ['oof']) {
        const filenames = getFilenamesForExtension(scenarioData, ext);
        for (const filename of filenames) {
            const dirPath = getDirectoryForExtension(ext);
            const fullFilename = `${filename}.${ext.toUpperCase()}`;
            scenarioOutput += `#include "${fullFilename}", "${dirPath}"\n`;
        }
    }
    scenarioOutput += '#include "AllLoad.INI", "INI\\"\n';
    for (const ext of ['oob']) {
        const filenames = getFilenamesForExtension(scenarioData, ext);
        for (const filename of filenames) {
            const dirPath = getDirectoryForExtension(ext);
            const fullFilename = `${filename}.${ext.toUpperCase()}`;
            scenarioOutput += `#include "${fullFilename}", "${dirPath}"\n`;
        }
    }

    // #ifset 0x04 section
    scenarioOutput += "#ifset 0x04\n";
    scenarioOutput += "&&SAV\n";
    const savFilenames = getFilenamesForExtension(scenarioData, 'sav');
    if (savFilenames.length > 0) {
        const savName = savFilenames[0].split('.')[0];
        scenarioOutput += `savfile "${savName}"\n`;
    }
    scenarioOutput += "&&END\n";
    scenarioOutput += "#endifset\n\n";

    // &&GMC section
    scenarioOutput += "&&GMC\n";
    for (const [key, value] of Object.entries(settingsData)) {
        scenarioOutput += formatGmcLine(key, value);
    }
    scenarioOutput += "&&END\n";

    return scenarioOutput;
}

function getDirectoryForExtension(ext) {
    const defaultStructure = DEFAULT_PROJECT_FILE_STRUCTURE;
    if (ext in defaultStructure) {
        let dirPath = defaultStructure[ext].dir;
        dirPath = dirPath.replace(/\//g, '\\').toUpperCase();
        if (dirPath && !dirPath.endsWith('\\')) {
            dirPath += '\\';
        }
        return dirPath;
    }
    return '';
}

function formatGmcLine(key, value) {
    let line = `${key}:\t\t\t`;
    if (Array.isArray(value)) {
        const valueStr = value.map(v => v !== null ? String(v) : '').join(', ');
        line += `${valueStr}\n`;
    } else {
        line += `${value}\n`;
    }
    return line;
}

// CVP Exporter
export function exportCvp(cvpData) {
    let cvpOutput = "// Generated CVP File\n\n";
    cvpOutput += writeTheaters(cvpData.Theaters_Data || {});
    cvpOutput += writeRegions(cvpData.Regions_Data || []);
    return cvpOutput;
}

function writeTheaters(theatersData) {
    if (!theatersData || Object.keys(theatersData).length === 0) {
        return '';
    }
    let theatresOutput = "&&THEATRES\n";
    for (const [theatreId, theatre] of Object.entries(theatersData)) {
        const theatreName = theatre.theatreName || '';
        const theatreCode = theatre.theatreCode || '';
        const culture = theatre.culture || 0;
        const xLocation = theatre.xLocation || 0;
        const yLocation = theatre.yLocation || 0;
        theatresOutput += `${theatreId}, ${theatreName}, ${theatreCode}, ${culture}, ${xLocation}, ${yLocation},\n`;
    }

    theatresOutput += "\n&&THEATRETRANSF\n";
    for (const [theatreId, theatre] of Object.entries(theatersData)) {
        const transferStr = (theatre.transfers || []).join(', ');
        const theatreName = theatre.theatreName || '';
        const theatreCode = theatre.theatreCode || '';
        theatresOutput += `${theatreId}, ${transferStr}                               // "${theatreName}", "${theatreCode}"\n`;
    }

    theatresOutput += "&&END\n\n";
    return theatresOutput;
}

function writeRegions(regionsData) {
    let regionsOutput = "";
    for (const region of regionsData) {
        const regionId = region.ID;
        regionsOutput += `&&CVP\t\t\t\t${regionId}\n`;
        regionsOutput += writeRegionProperties(region.Properties);
        regionsOutput += writeGrouping(region.grouping || [], regionId);
        regionsOutput += writeRegiontechs(region.regiontechs || [], regionId);
        regionsOutput += writeRegionunitdesigns(region.regionunitdesigns || [], regionId);
        regionsOutput += writeRegionproducts(region.regionproducts || [], regionId);
        regionsOutput += writeRegionsocials(region.regionsocials || [], regionId);
        regionsOutput += writeRegionreligions(region.regionreligions || [], regionId);
    }
    return regionsOutput;
}

const ALL_PROPERTY_LABELS = [
    'regionname', 'prefixname', 'altregionname', 'blocknum', 'altblocknum',
    'continentnum', 'flagnum', 'musictrack', 'regioncolor', 'politic', 'govtype',
    'refpopulation', 'poptotalarmy', 'popminreserve', 'treasury', 'nationaldebtgdp',
    'techlevel', 'civapproval', 'milapproval', 'fanaticism', 'defcon', 'loyalty',
    'playeragenda', 'playeraistance', 'worldavail', 'armsavail', 'worldintegrity',
    'treatyintegrity', 'envrating', 'milsubsidyrating', 'domsubsidyrating',
    'creditrating', 'tourismrating', 'literacy', 'lifeexp', 'avgchildren',
    'crimerate', 'unemployment', 'gdpc', 'inflation', 'buyingpower',
    'prodefficiency', 'alertlevel', 'bwmmember', 'religionstate', 'bconscript',
    'forcesplan', 'milspendsalary', 'milspendmaint', 'milspendintel',
    'milspendresearch', 'RacePrimary', 'RaceSecondary', 'capitalx', 'capitaly',
    'masterdata', 'nonplayable', 'influence', 'influenceval', 'couppossibility',
    'revoltpossibility', 'independencedesire', 'parentloyalty',
    'independencetarget', 'sphere', 'civiliansphere', 'keepregion', 'parentregion',
    'theatrehome', 'electiondate'
];

function writeRegionProperties(properties) {
    let output = "";
    for (const key of ALL_PROPERTY_LABELS) {
        const value = properties[key];
        if (Array.isArray(value)) {
            const valueStr = value.map(x => x !== null ? String(x) : '').join(', ');
            output += `${key}\t\t\t\t${valueStr}\n`;
        } else {
            if (value === null || value === undefined) {
                output += `${key}\n`;
            } else if (typeof value === 'string' && value.startsWith('0x')) {
                output += `${key}\t\t\t\t${value}\n`;
            } else if (typeof value === 'number') {
                output += `${key}\t\t\t\t${Number.isInteger(value) ? parseInt(value) : value}\n`;
            } else {
                output += `${key}\t\t\t\t"${value}"\n`;
            }
        }
    }
    return output;
}

function writeGrouping(grouping, regionId) {
    if (grouping && grouping.length > 0) {
        const groupingStr = grouping.map(String).join(',\n') + ',\n';
        return `&&GROUPING\t\t\t\t${regionId}\n${groupingStr}\n`;
    }
    return `&&GROUPING\t\t\t\t${regionId}\n\n`;
}

function writeRegiontechs(regiontechs, regionId) {
    if (regiontechs && regiontechs.length > 0) {
        const regiontechsStr = regiontechs.map(String).join(',\n') + ',\n';
        return `&&REGIONTECHS\t\t\t${regionId}\n${regiontechsStr}\n`;
    }
    return `&&REGIONTECHS\t\t\t${regionId}\n\n`;
}

function writeRegionunitdesigns(regionunitdesigns, regionId) {
    if (regionunitdesigns && regionunitdesigns.length > 0) {
        const regionunitdesignsStr = regionunitdesigns.map(String).join(',\n') + ',\n';
        return `&&REGIONUNITDESIGNS\t${regionId}\n${regionunitdesignsStr}\n`;
    }
    return `&&REGIONUNITDESIGNS\t${regionId}\n\n`;
}

function writeRegionproducts(regionproducts, regionId) {
    if (regionproducts && regionproducts.length > 0) {
        let productsOutput = `&&REGIONPRODUCTS\t\t${regionId}\n`;
        for (const product of regionproducts) {
            const productStr = product.map(x => x !== null ? String(x) : '').join(', ');
            productsOutput += `${productStr},\n`;
        }
        return productsOutput + '\n';
    }
    return `&&REGIONPRODUCTS\t\t${regionId}\n\n`;
}

function writeRegionsocials(regionsocials, regionId) {
    if (regionsocials && regionsocials.length > 0) {
        let socialsOutput = `&&REGIONSOCIALS\t\t${regionId}\n`;
        for (const social of regionsocials) {
            const socialStr = social.map(x => x !== null ? String(x) : '').join(', ');
            socialsOutput += `${socialStr},\n`;
        }
        return socialsOutput + '\n';
    }
    return `&&REGIONSOCIALS\t\t${regionId}\n\n`;
}

function writeRegionreligions(regionreligions, regionId) {
    if (regionreligions && regionreligions.length > 0) {
        let religionsOutput = `&&REGIONRELIGIONS\t${regionId}\n`;
        for (const religion of regionreligions) {
            const religionStr = religion.map(x => {
                return x === parseInt(x) ? String(parseInt(x)) : parseFloat(x).toPrecision(6);
            }).join(', ');
            religionsOutput += `${religionStr},\n`;
        }
        return religionsOutput + '\n';
    }
    return `&&REGIONRELIGIONS\t${regionId}\n\n`;
}

// OOB Exporter
export function exportOob(oobData) {
    let oobOutput = "// Generated OOB File\n\n";
    const oobDataList = oobData.OOB_Data || [];
    for (const region of oobDataList) {
        oobOutput += writeOobRegion(region);
    }
    return oobOutput;
}

function writeOobRegion(region) {
    let regionOutput = `&&OOB ${region.regionId}\n`;
    regionOutput += writeOobUnits(region.units);
    return regionOutput + '\n';
}

function writeOobUnits(units) {
    let unitsOutput = "";
    const unitKeys = [
        "unitId", "X", "Y", "LocName", "Quantity", "Status", "BattNum", "BattName",
        "Entrench", "Eff", "Exp", "Special", "Str", "MaxStr", "DaysLeft", "Facing",
        "GroupId", "TargetRole", "StatustoBattC", "StatustoBattN"
    ];
    for (const unit of units) {
        const unitStr = unitKeys.map(key => {
            const val = unit[key];
            return val !== null && val !== undefined ? String(val) : '';
        }).join(', ');
        unitsOutput += `${unitStr},\n`;
    }
    return unitsOutput;
}

// REGIONINCL Exporter
export function exportRegionincl(regioninclData) {
    let regioninclOutput = "// Generated REGIONINCL File\n\n&&REGIONINCL\n";

    for (const region of regioninclData.regions || []) {
        if (region.isActive) {
            if (region.comment) {
                regioninclOutput += `${region.regionId}    //    ${region.comment}\n`;
            } else {
                regioninclOutput += `${region.regionId}\n`;
            }
        } else {
            if (region.comment) {
                regioninclOutput += `// ${region.regionId}    //    ${region.comment}\n`;
            } else {
                regioninclOutput += `// ${region.regionId}\n`;
            }
        }
    }

    return regioninclOutput;
}

// WMDATA Exporter
const RESOURCE_TO_ID = {
    "agriculture": 0,
    "rubber": 1,
    "timber": 2,
    "petroleum": 3,
    "coal": 4,
    "ore": 5,
    "uranium": 6,
    "electricity": 7,
    "consumergoods": 8,
    "militarygoods": 9,
    "industrialgoods": 10
};

const ID_TO_RESOURCE = {
    0: "agriculture",
    1: "rubber",
    2: "timber",
    3: "petroleum",
    4: "coal",
    5: "ore",
    6: "uranium",
    7: "electricity",
    8: "consumergoods",
    9: "militarygoods",
    10: "industrialgoods"
};

const BATTSTRDEFAULT_LABELS = [
    "inf", "rec", "tank", "at", "art", "aa", "trp", "helo", "miss", "int",
    "fig", "multi", "bomb", "rec_air", "a-trp", "sub", "carr", "bship", "frig",
    "spat", "strp", "upgrade", "unused"
];

const SOCIALDEFAULTS_LABELS = [
    "healthcare", "education", "familysubsidy", "lawenforcement",
    "infrastructure", "socialassistance", "culturalsubsidy", "environment"
];

const HEXRESMULTS_LABELS = [
    "agriculture", "rubber", "timber", "petroleum", "coal", "ore", "uranium", "electricity"
];

export function exportWmdata(wmdataJson) {
    let wmdataOutput = "// Generated WMDATA File\n\n&&WMDATA 0\n";

    const worldmarket = wmdataJson.worldmarket || {};
    const settings = worldmarket.settings || {};
    const military = worldmarket.military || {};
    const economic = worldmarket.economic || {};
    const weather = worldmarket.weather || {};

    // Write settings
    const settingsOrder = ["dayswmlevel", "wmlevel", "gdpcbase", "primerate", "socadj", "wmrelrate"];
    for (const key of settingsOrder) {
        const value = settings[key];
        if (value !== undefined && value !== null) {
            wmdataOutput += `${key}, ${value},\n`;
        }
    }

    // Write military
    if (military.unitgarrison) {
        const valueStr = military.unitgarrison.map(String).join(', ') + ',';
        wmdataOutput += `unitgarrison, ${valueStr}\n`;
    }
    if (military.battstrdefault) {
        const valueStr = BATTSTRDEFAULT_LABELS.map(label =>
            String(military.battstrdefault[label] || '')
        ).join(',\t') + ',';
        wmdataOutput += `battstrdefault, ${valueStr}\n`;
    }

    // Write economic
    if (economic.hexresmults) {
        const valueStr = HEXRESMULTS_LABELS.map(label =>
            String(economic.hexresmults[label] || 0)
        ).join(', ') + ',';
        wmdataOutput += `hexresmults, ${valueStr}\n`;
    }
    if (economic.socialdefaults) {
        const valueStr = SOCIALDEFAULTS_LABELS.map(label =>
            String(economic.socialdefaults[label] || 0)
        ).join(', ') + ',';
        wmdataOutput += `socialdefaults, ${valueStr}\n`;
    }

    // Write weather
    const weatherOrder = ["weatheryear", "weatheroffy", "weatherspeed", "days"];
    for (const key of weatherOrder) {
        const value = weather[key];
        if (value !== undefined && value !== null) {
            if (Array.isArray(value)) {
                const valueStr = value.map(String).join(', ') + ',';
                wmdataOutput += `${key}, ${valueStr}\n`;
            } else {
                wmdataOutput += `${key}, ${value},\n`;
            }
        }
    }

    wmdataOutput += "&&END\n\n";

    // Write resource production data
    const resources = wmdataJson.resources || {};
    for (const [resource, details] of Object.entries(resources)) {
        const resourceId = RESOURCE_TO_ID[resource];
        if (resourceId !== undefined) {
            wmdataOutput += `&&WMPRODDATA, ${resourceId}\n`;

            // Write producefrom
            if (details.producefrom) {
                const valueStr = Object.values(ID_TO_RESOURCE).map(label =>
                    String(details.producefrom[label] || 0)
                ).join(', ') + ',';
                wmdataOutput += `producefrom, ${valueStr}\n`;
            }

            // Write cost
            const cost = details.cost || {};
            const costOrder = ["wmbasecost", "wmfullcost", "wmmargin"];
            for (const key of costOrder) {
                const value = cost[key];
                if (value !== undefined && value !== null) {
                    wmdataOutput += `${key}, ${value},\n`;
                }
            }

            // Write production
            const production = details.production || {};
            const productionOrder = ["wmprodperpersonmax", "wmprodperpersonmin", "wmurbanproduction", "nodeproduction"];
            for (const key of productionOrder) {
                const value = production[key];
                if (value !== undefined && value !== null) {
                    wmdataOutput += `${key}, ${value},\n`;
                }
            }

            wmdataOutput += "&&END\n\n";
        }
    }

    return wmdataOutput;
}
